### ISSUE TITLE
Make logs format identical

### ISSUE THREAD

**Issue by SKY-ALIN** [vsezol/space-drive-visualizer#17]
Current state:
```bash
space-drive-game        | [2024-02-20T10:56:06Z INFO  space_drive_game_server] Server is running on 127.0.0.1:3333
space-drive-visualizer  | [Nest] 1  - 02/20/2024, 10:56:06 AM     LOG [NestFactory] Starting Nest application...
space-drive-visualizer  | [Nest] 1  - 02/20/2024, 10:56:06 AM     LOG [InstanceLoader] AppModule dependencies initialized +26ms
space-drive-visualizer  | [Nest] 1  - 02/20/2024, 10:56:06 AM     LOG [InstanceLoader] VideosModule dependencies initialized +0ms
space-drive-visualizer  | [Nest] 1  - 02/20/2024, 10:56:06 AM     LOG [RoutesResolver] VideosController {/api/videos}: +5ms
space-drive-visualizer  | [Nest] 1  - 02/20/2024, 10:56:06 AM     LOG [RouterExplorer] Mapped {/api/videos/render, POST} route +2ms
space-drive-visualizer  | [Nest] 1  - 02/20/2024, 10:56:06 AM     LOG [NestApplication] Nest application successfully started +1ms
space-drive-visualizer  | [Nest] 1  - 02/20/2024, 10:56:06 AM     LOG 🚀 Application is running on: http://localhost:3000/api
```

**Comment by vsezol** [comment]
@SKY-ALIN Что тебе не понравилось в логах?

**Comment by SKY-ALIN** [comment]
Было бы здорово привести их к общему формату, смотрелось бы очень красиво

**Comment by vsezol** [comment]
@SKY-ALIN это же разные сервисы на разных языках, не вижу смысла приведения логов к единому формату.

**Comment by SKY-ALIN** [comment]
Если они на разных языках и выполняют разные функции, то это не аргумент чтобы их не нормализировать. Логи принято выводить с указанием уровня, таймстемпа, и т д

Игроки перед тем как участвовать будут все дебажить и локально поднимать наши сервисы. Будут видеть )

**Comment by vsezol** [comment]
@SKY-ALIN не понимаю, какая пользователям разница. Пользователи, которые зачем-то будут разворачивать локально, а не пользоваться просто развернутым тестовым сервером, сами себе усложняют жизнь. Логи не для пользователей, для них есть ошибки и корректные сообщения.

**Comment by SKY-ALIN** [comment]
Elk тут не при чем. Если не хотите, то ок, можете закрыть ишью. Просто мне показалось, что это было бы элегантно и правильно
